layout_spectrum: 0.9146079
color:
  saturation: 0.06206354
  brandStrength: 0.5485229
  lightness: 0.8958382
  brandColors:
    - '#201F1E'
    - '#5C6D91'
    - '#E0E0E1'
    - '#80BDE0'
    - '#BD886E'
  rhythmicContrast: 0.8329839
typography_spectrum: 0.5010741
name: Apex Center of Excellence
